GRANT SELECT, INSERT, UPDATE, DELETE ON 
com_college_human,
com_fund,
com_standing,
com_standard_pay,
coa_adopt_item,
coa_standing_time,
cod_address_request,
cod_adopt_request,
cod_college_attendance,
cod_payment,
cod_standing_attendance,
cot_standing_attendance_time,
cod_college_holiday,
cod_total_college,
cod_total_standing, 
com_college_allocation,
com_college_setting,
cod_total_standing,
cod_prospects_total_standing,
cod_prospects_college_attendance,
cod_prospects_standing_attendance,
cod_prospects_total_college,
cod_prospects_college_holiday,
cot_prospects_standing_attendance_time,
cod_transportation_request,
coa_transportation_route,
coa_user_onetime_password,
cod_password_request
 TO usermosp;

GRANT USAGE, SELECT, UPDATE ON 
com_college_allocation_id_seq,
com_college_human_id_seq,
com_fund_id_seq,
com_standard_pay_id_seq,
com_standing_id_seq,
com_standing_standing_code_seq,
coa_adopt_item_id_seq,
coa_standing_time_id_seq,
cod_address_request_id_seq,
cod_adopt_request_id_seq,
cod_adopt_request_adopt_code_seq,
cod_college_attendance_id_seq,
cod_payment_id_seq,
cod_standing_attendance_id_seq,
cot_standing_attendance_time_id_seq,
cod_college_holiday_id_seq,
cod_total_college_id_seq,
cod_total_standing_id_seq, 
com_college_setting_id_seq,
cod_total_standing_id_seq ,
cod_prospects_total_standing_id_seq,
cod_prospects_college_attendance_id_seq,
cod_prospects_standing_attendance_id_seq,
cod_prospects_total_college_id_seq,
cod_prospects_college_holiday_id_seq,
cot_prospects_standing_attendance_time_id_seq,
cod_transportation_request_id_seq,
coa_transportation_route_id_seq,
coa_user_onetime_password_id_seq,
cod_password_request_id_seq
 TO usermosp;
